version: '3'
services:

  api:
    build: ./api
    image: node-express:1.0
    container_name: api
    tty: true
    volumes:
      - ./api/source:/api
    ports:
      - 3000:3000

  webpack:
    build: ./webpack
    image: webpack:1.0
    container_name: webpack_container
    ports:
      - 8000:8000
    volumes:
      - ./webpack/webpack.config.js:/app/webpack.config.js
      - ./webpack/.babelrc:/app/.babelrc
      - ./webpack/package.json:/app/package.json
      - ./app/src:/app/src:ro
      - ./app/dist:/app/dist:z

  nginx:
    build: ./nginx
    image: nginx:1.0
    container_name: nginx_container
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app/dist:/var/www/develop:ro
    depends_on:
      - php

  php:
    build: ./php
    image: php-fpm:1.0
    container_name: php-fpm_container
    env_file: .env
    volumes:
      - ./app/dist:/var/www/develop:ro
    depends_on:
      - db

  db:
    build: ./mysql
    image: mysql:1.0
    user: '1000:50'
    command: '--innodb_use_native_aio=0'
    container_name: mysql_container
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./mysql/app.cnf:/etc/mysql/conf.d/app.cnf
      - ./mysql/data:/var/lib/mysql
